---
items:
  - name: Bier 1
    key: bier1
  - name: Bier 2
    key: bier2
  - name: Leckeres Bier
    key: bier3
questions:
  - name: "Farbe"
    key: "farbe"
  - name: "Geruch"
    key: "geruch"
  - name: "Bitterkeit"
    key: "bitterkeit"
  - name: "Gesamtbewertung"
    key: "gesamtbewertung"
texts:
  title: "Tasting!"
  jumbo: "<h1>Welcome to our tasting event!</h1> Click on the stars to give your rating or leave comments for other attendees."
